### ISSUE TITLE
Unable to Build or Run

### ISSUE THREAD

**Issue by tezine** [polyglot-microfrontends/navbar#4]
Hi, 
This repository doesn't compile or run. Whenever I try to run it, I get the errors below:
```
ERROR in ./src/primary-nav/primary-nav.css (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/style-loader/dist/cjs.js!./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/css-loader/dist/cjs.js??ref--7-2
!./src/primary-nav/primary-nav.css)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
CssSyntaxError

(1:1) Unknown word

> 1 | var api = require("!../../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js");
    | ^
  2 |             var content = require("!!../../node_modules/css-loader/dist/cjs.js??ref--7-1!../../node_modules/css-loader/dist/cjs.js??ref--7-2!./primary-nav.css");
```

**Comment by internettrans** [comment]
I tried it out locally and it is working for me, so it must be a different in our environments. First thing to check is that you're running `yarn install` instead of `npm install`. Second thing is to check which version of `node` and `npm` you are using. I am using NodeJS 13.14.0 and NPM 6.14.4

**Comment by xkelvinx666** [comment]
I tried to use in Node 13.14.0 and NPM 6.14.4 
```
npm install
npm run build
```
It failed

<img width="939" alt="image" src="https://user-images.githubusercontent.com/15306173/92065878-171ed380-edd3-11ea-932d-cc94cb48bcf0.png">

However

```
yarn install
npm run build
```

It worked

<img width="823" alt="image" src="https://user-images.githubusercontent.com/15306173/92066061-91e7ee80-edd3-11ea-9d0d-b2b83e3c17ac.png">

**Comment by internettrans** [comment]
Glad to hear it worked with yarn
